spring:
  application:
    name: account-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: account-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cmdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ops.account.entity
  configuration:
    map-underscore-to-camel: true

server:
  port: 8504
pagehelper:
  helper-dialect: mysql
  reasonable: treu
  support-methods-arguments: true