spring:
  appliction:
    name: admin-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: admin-service
        instance-id: admin-service
  boot:
    admin:
      discovery:
        ignored-services: consul
server:
  port: 8505